name: flare-constructor
version: '1.0-SNAPSHOT'
main: net.kassin.flareconstructor.FlareConstructorPlugin
api-version: '1.21'
depend:
  - FastAsyncWorldEdit
softdepend:
  - ItemsAdder
commands:
  build:
    description: Constrói uma schematic camada por camada
    usage: /build <schematic> [delayTicks] [blocksPerTick]
    permission: flareconstructor.build
  buildcancel:
    description: Cancela a construção em andamento
    usage: /buildcancel [undo]
    permission: flareconstructor.build